config/routes.rb
Rails.application.routes.draw do
  resources :tipomonedas
  resources :tipomonedas
  resources :tipomonedas
  resources :tipocuenta
  resources :tamanoempresas
  resources :supervisors
  resources :solicitudinformes
  resources :nivelriesgos
  resources :institucionfinancieras
  resources :informacioncontables
  resources :informacioncomercialclientes
  resources :informacioncomercials
  resources :estudioriesgos
  resources :estadoprocesos
  resources :estadoclientes
  resources :empresas
  resources :empleados
  resources :ejecutivos
  resources :cuentacontables
  resources :contienens
  resources :clientes
  resources :certificadoriesgos
  resources :avalesencertificadoriesgos
  resources :avals
  resources :articles
  resources :analista
  resources :articles

end

app/models/analistum.rb
class Analistum < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/aval.rb
class Aval < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/contienen.rb
class Contienen < ActiveRecord::Base
end

app/models/cuentacontable.rb
class Cuentacontable < ActiveRecord::Base
end

app/models/ejecutivo.rb
class Ejecutivo < ActiveRecord::Base
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estadocliente.rb
class Estadocliente < ActiveRecord::Base
end

app/models/estadoproceso.rb
class Estadoproceso < ActiveRecord::Base
end

app/models/estudioriesgo.rb
class Estudioriesgo < ActiveRecord::Base
end

app/models/nivelriesgo.rb
class Nivelriesgo < ActiveRecord::Base
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
end

app/models/tamanoempresa.rb
class Tamanoempresa < ActiveRecord::Base
end

app/models/tipocuentum.rb
class Tipocuentum < ActiveRecord::Base
end

app/models/tipomoneda.rb
class Tipomoneda < ActiveRecord::Base
end

app/controllers/contienens_controller.rb
class ContienensController < ApplicationController
  before_action :set_contienen, only: [:show, :edit, :update, :destroy]

  # GET /contienens
  # GET /contienens.json
  def index
    @contienens = Contienen.all
  end

  # GET /contienens/1
  # GET /contienens/1.json
  def show
  end

  # GET /contienens/new
  def new
    @contienen = Contienen.new
  end

  # GET /contienens/1/edit
  def edit
  end

  # POST /contienens
  # POST /contienens.json
  def create
    @contienen = Contienen.new(contienen_params)

    respond_to do |format|
      if @contienen.save
        format.html { redirect_to @contienen, notice: 'Contienen was successfully created.' }
        format.json { render :show, status: :created, location: @contienen }
      else
        format.html { render :new }
        format.json { render json: @contienen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contienens/1
  # PATCH/PUT /contienens/1.json
  def update
    respond_to do |format|
      if @contienen.update(contienen_params)
        format.html { redirect_to @contienen, notice: 'Contienen was successfully updated.' }
        format.json { render :show, status: :ok, location: @contienen }
      else
        format.html { render :edit }
        format.json { render json: @contienen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contienens/1
  # DELETE /contienens/1.json
  def destroy
    @contienen.destroy
    respond_to do |format|
      format.html { redirect_to contienens_url, notice: 'Contienen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contienen
      @contienen = Contienen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contienen_params
      params.require(:contienen).permit(:foliocertificadoriesgo, :idavalesencertificados)
    end
end

app/helpers/analista_helper.rb
module AnalistaHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avals_helper.rb
module AvalsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contienens_helper.rb
module ContienensHelper
end

app/views/contienens/_form.html.erb
<%= form_for(@contienen) do |f| %>
  <% if @contienen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contienen.errors.count, "error") %> prohibited this contienen from being saved:</h2>

      <ul>
      <% @contienen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foliocertificadoriesgo %><br>
    <%= f.text_field :foliocertificadoriesgo %>
  </div>
  <div class="field">
    <%= f.label :idavalesencertificados %><br>
    <%= f.number_field :idavalesencertificados %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contienens/edit.html.erb
<h1>Editing Contienen</h1>

<%= render 'form' %>

<%= link_to 'Show', @contienen %> |
<%= link_to 'Back', contienens_path %>

app/views/contienens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contienens</h1>

<table>
  <thead>
    <tr>
      <th>Foliocertificadoriesgo</th>
      <th>Idavalesencertificados</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contienens.each do |contienen| %>
      <tr>
        <td><%= contienen.foliocertificadoriesgo %></td>
        <td><%= contienen.idavalesencertificados %></td>
        <td><%= link_to 'Show', contienen %></td>
        <td><%= link_to 'Edit', edit_contienen_path(contienen) %></td>
        <td><%= link_to 'Destroy', contienen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contienen', new_contienen_path %>

app/views/contienens/new.html.erb
<h1>New Contienen</h1>

<%= render 'form' %>

<%= link_to 'Back', contienens_path %>

app/views/contienens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foliocertificadoriesgo:</strong>
  <%= @contienen.foliocertificadoriesgo %>
</p>

<p>
  <strong>Idavalesencertificados:</strong>
  <%= @contienen.idavalesencertificados %>
</p>

<%= link_to 'Edit', edit_contienen_path(@contienen) %> |
<%= link_to 'Back', contienens_path %>