config/routes.rb
Rails.application.routes.draw do
  resources :tipomonedas
  resources :tipomonedas
  resources :tipomonedas
  resources :tipocuenta
  resources :tamanoempresas
  resources :supervisors
  resources :solicitudinformes
  resources :nivelriesgos
  resources :institucionfinancieras
  resources :informacioncontables
  resources :informacioncomercialclientes
  resources :informacioncomercials
  resources :estudioriesgos
  resources :estadoprocesos
  resources :estadoclientes
  resources :empresas
  resources :empleados
  resources :ejecutivos
  resources :cuentacontables
  resources :contienens
  resources :clientes
  resources :certificadoriesgos
  resources :avalesencertificadoriesgos
  resources :avals
  resources :articles
  resources :analista
  resources :articles

end

app/models/analistum.rb
class Analistum < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/aval.rb
class Aval < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/contienen.rb
class Contienen < ActiveRecord::Base
end

app/models/cuentacontable.rb
class Cuentacontable < ActiveRecord::Base
end

app/models/ejecutivo.rb
class Ejecutivo < ActiveRecord::Base
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estadocliente.rb
class Estadocliente < ActiveRecord::Base
end

app/models/estadoproceso.rb
class Estadoproceso < ActiveRecord::Base
end

app/models/estudioriesgo.rb
class Estudioriesgo < ActiveRecord::Base
end

app/models/nivelriesgo.rb
class Nivelriesgo < ActiveRecord::Base
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
end

app/models/tamanoempresa.rb
class Tamanoempresa < ActiveRecord::Base
end

app/models/tipocuentum.rb
class Tipocuentum < ActiveRecord::Base
end

app/models/tipomoneda.rb
class Tipomoneda < ActiveRecord::Base
end

app/controllers/estudioriesgos_controller.rb
class EstudioriesgosController < ApplicationController
  before_action :set_estudioriesgo, only: [:show, :edit, :update, :destroy]

  # GET /estudioriesgos
  # GET /estudioriesgos.json
  def index
    @estudioriesgos = Estudioriesgo.all
  end

  # GET /estudioriesgos/1
  # GET /estudioriesgos/1.json
  def show
  end

  # GET /estudioriesgos/new
  def new
    @estudioriesgo = Estudioriesgo.new
  end

  # GET /estudioriesgos/1/edit
  def edit
  end

  # POST /estudioriesgos
  # POST /estudioriesgos.json
  def create
    @estudioriesgo = Estudioriesgo.new(estudioriesgo_params)

    respond_to do |format|
      if @estudioriesgo.save
        format.html { redirect_to @estudioriesgo, notice: 'Estudioriesgo was successfully created.' }
        format.json { render :show, status: :created, location: @estudioriesgo }
      else
        format.html { render :new }
        format.json { render json: @estudioriesgo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudioriesgos/1
  # PATCH/PUT /estudioriesgos/1.json
  def update
    respond_to do |format|
      if @estudioriesgo.update(estudioriesgo_params)
        format.html { redirect_to @estudioriesgo, notice: 'Estudioriesgo was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudioriesgo }
      else
        format.html { render :edit }
        format.json { render json: @estudioriesgo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudioriesgos/1
  # DELETE /estudioriesgos/1.json
  def destroy
    @estudioriesgo.destroy
    respond_to do |format|
      format.html { redirect_to estudioriesgos_url, notice: 'Estudioriesgo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudioriesgo
      @estudioriesgo = Estudioriesgo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudioriesgo_params
      params.require(:estudioriesgo).permit(:idestadoproceso, :idanalista, :fechainicioestudioriesgo, :fechaterminoestudioriesgo, :observacionestudio)
    end
end

app/helpers/analista_helper.rb
module AnalistaHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avals_helper.rb
module AvalsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estudioriesgos_helper.rb
module EstudioriesgosHelper
end

app/views/estudioriesgos/_form.html.erb
<%= form_for(@estudioriesgo) do |f| %>
  <% if @estudioriesgo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estudioriesgo.errors.count, "error") %> prohibited this estudioriesgo from being saved:</h2>

      <ul>
      <% @estudioriesgo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idestadoproceso %><br>
    <%= f.number_field :idestadoproceso %>
  </div>
  <div class="field">
    <%= f.label :idanalista %><br>
    <%= f.number_field :idanalista %>
  </div>
  <div class="field">
    <%= f.label :fechainicioestudioriesgo %><br>
    <%= f.date_select :fechainicioestudioriesgo %>
  </div>
  <div class="field">
    <%= f.label :fechaterminoestudioriesgo %><br>
    <%= f.date_select :fechaterminoestudioriesgo %>
  </div>
  <div class="field">
    <%= f.label :observacionestudio %><br>
    <%= f.text_area :observacionestudio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estudioriesgos/edit.html.erb
<h1>Editing Estudioriesgo</h1>

<%= render 'form' %>

<%= link_to 'Show', @estudioriesgo %> |
<%= link_to 'Back', estudioriesgos_path %>

app/views/estudioriesgos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estudioriesgos</h1>

<table>
  <thead>
    <tr>
      <th>Idestadoproceso</th>
      <th>Idanalista</th>
      <th>Fechainicioestudioriesgo</th>
      <th>Fechaterminoestudioriesgo</th>
      <th>Observacionestudio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudioriesgos.each do |estudioriesgo| %>
      <tr>
        <td><%= estudioriesgo.idestadoproceso %></td>
        <td><%= estudioriesgo.idanalista %></td>
        <td><%= estudioriesgo.fechainicioestudioriesgo %></td>
        <td><%= estudioriesgo.fechaterminoestudioriesgo %></td>
        <td><%= estudioriesgo.observacionestudio %></td>
        <td><%= link_to 'Show', estudioriesgo %></td>
        <td><%= link_to 'Edit', edit_estudioriesgo_path(estudioriesgo) %></td>
        <td><%= link_to 'Destroy', estudioriesgo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudioriesgo', new_estudioriesgo_path %>

app/views/estudioriesgos/new.html.erb
<h1>New Estudioriesgo</h1>

<%= render 'form' %>

<%= link_to 'Back', estudioriesgos_path %>

app/views/estudioriesgos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idestadoproceso:</strong>
  <%= @estudioriesgo.idestadoproceso %>
</p>

<p>
  <strong>Idanalista:</strong>
  <%= @estudioriesgo.idanalista %>
</p>

<p>
  <strong>Fechainicioestudioriesgo:</strong>
  <%= @estudioriesgo.fechainicioestudioriesgo %>
</p>

<p>
  <strong>Fechaterminoestudioriesgo:</strong>
  <%= @estudioriesgo.fechaterminoestudioriesgo %>
</p>

<p>
  <strong>Observacionestudio:</strong>
  <%= @estudioriesgo.observacionestudio %>
</p>

<%= link_to 'Edit', edit_estudioriesgo_path(@estudioriesgo) %> |
<%= link_to 'Back', estudioriesgos_path %>