config/routes.rb
Rails.application.routes.draw do
  resources :tipomonedas
  resources :tipomonedas
  resources :tipomonedas
  resources :tipocuenta
  resources :tamanoempresas
  resources :supervisors
  resources :solicitudinformes
  resources :nivelriesgos
  resources :institucionfinancieras
  resources :informacioncontables
  resources :informacioncomercialclientes
  resources :informacioncomercials
  resources :estudioriesgos
  resources :estadoprocesos
  resources :estadoclientes
  resources :empresas
  resources :empleados
  resources :ejecutivos
  resources :cuentacontables
  resources :contienens
  resources :clientes
  resources :certificadoriesgos
  resources :avalesencertificadoriesgos
  resources :avals
  resources :articles
  resources :analista
  resources :articles

end

app/models/analistum.rb
class Analistum < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/aval.rb
class Aval < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/contienen.rb
class Contienen < ActiveRecord::Base
end

app/models/cuentacontable.rb
class Cuentacontable < ActiveRecord::Base
end

app/models/ejecutivo.rb
class Ejecutivo < ActiveRecord::Base
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estadocliente.rb
class Estadocliente < ActiveRecord::Base
end

app/models/estadoproceso.rb
class Estadoproceso < ActiveRecord::Base
end

app/models/estudioriesgo.rb
class Estudioriesgo < ActiveRecord::Base
end

app/models/nivelriesgo.rb
class Nivelriesgo < ActiveRecord::Base
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
end

app/models/tamanoempresa.rb
class Tamanoempresa < ActiveRecord::Base
end

app/models/tipocuentum.rb
class Tipocuentum < ActiveRecord::Base
end

app/models/tipomoneda.rb
class Tipomoneda < ActiveRecord::Base
end

app/controllers/estadoclientes_controller.rb
class EstadoclientesController < ApplicationController
  before_action :set_estadocliente, only: [:show, :edit, :update, :destroy]

  # GET /estadoclientes
  # GET /estadoclientes.json
  def index
    @estadoclientes = Estadocliente.all
  end

  # GET /estadoclientes/1
  # GET /estadoclientes/1.json
  def show
  end

  # GET /estadoclientes/new
  def new
    @estadocliente = Estadocliente.new
  end

  # GET /estadoclientes/1/edit
  def edit
  end

  # POST /estadoclientes
  # POST /estadoclientes.json
  def create
    @estadocliente = Estadocliente.new(estadocliente_params)

    respond_to do |format|
      if @estadocliente.save
        format.html { redirect_to @estadocliente, notice: 'Estadocliente was successfully created.' }
        format.json { render :show, status: :created, location: @estadocliente }
      else
        format.html { render :new }
        format.json { render json: @estadocliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estadoclientes/1
  # PATCH/PUT /estadoclientes/1.json
  def update
    respond_to do |format|
      if @estadocliente.update(estadocliente_params)
        format.html { redirect_to @estadocliente, notice: 'Estadocliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @estadocliente }
      else
        format.html { render :edit }
        format.json { render json: @estadocliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estadoclientes/1
  # DELETE /estadoclientes/1.json
  def destroy
    @estadocliente.destroy
    respond_to do |format|
      format.html { redirect_to estadoclientes_url, notice: 'Estadocliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estadocliente
      @estadocliente = Estadocliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estadocliente_params
      params.require(:estadocliente).permit(:nombreestadocliente, :fechaingresoestadoclie)
    end
end

app/helpers/analista_helper.rb
module AnalistaHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avals_helper.rb
module AvalsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estadoclientes_helper.rb
module EstadoclientesHelper
end

app/views/estadoclientes/_form.html.erb
<%= form_for(@estadocliente) do |f| %>
  <% if @estadocliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estadocliente.errors.count, "error") %> prohibited this estadocliente from being saved:</h2>

      <ul>
      <% @estadocliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombreestadocliente %><br>
    <%= f.text_area :nombreestadocliente %>
  </div>
  <div class="field">
    <%= f.label :fechaingresoestadoclie %><br>
    <%= f.date_select :fechaingresoestadoclie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estadoclientes/edit.html.erb
<h1>Editing Estadocliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @estadocliente %> |
<%= link_to 'Back', estadoclientes_path %>

app/views/estadoclientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estadoclientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombreestadocliente</th>
      <th>Fechaingresoestadoclie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estadoclientes.each do |estadocliente| %>
      <tr>
        <td><%= estadocliente.nombreestadocliente %></td>
        <td><%= estadocliente.fechaingresoestadoclie %></td>
        <td><%= link_to 'Show', estadocliente %></td>
        <td><%= link_to 'Edit', edit_estadocliente_path(estadocliente) %></td>
        <td><%= link_to 'Destroy', estadocliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estadocliente', new_estadocliente_path %>

app/views/estadoclientes/new.html.erb
<h1>New Estadocliente</h1>

<%= render 'form' %>

<%= link_to 'Back', estadoclientes_path %>

app/views/estadoclientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombreestadocliente:</strong>
  <%= @estadocliente.nombreestadocliente %>
</p>

<p>
  <strong>Fechaingresoestadoclie:</strong>
  <%= @estadocliente.fechaingresoestadoclie %>
</p>

<%= link_to 'Edit', edit_estadocliente_path(@estadocliente) %> |
<%= link_to 'Back', estadoclientes_path %>